### PR TITLE
[Support] Defect - Investigate into issue #60 Downloading data triggers figure download

### PR DESCRIPTION
**Pull request by quentinGI**

### CODE REVIEW

**Review by gi-liam — APPROVED** [review]
The downloads work as expected, only the data is downloaded and the image pop no longer appears when clicking the download icon.

**Review by doug-leasure — CHANGES_REQUESTED** [review]
Thank you, @quentinGI!  This all looks good, with one small glitch remaining. The download data buttons are working for the bubble, doughnut, and choropleth. However, there are bugs with the download for the timeseries and the main download button in the navbar at the top of the page. 

Even after rebuilding the data from scratch, the traceback for the timeseries plot is: 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/app/app/routes.py", line 63, in getCSV
    return send_file('data/todownload/'+filename+'.zip')
  File "/usr/local/lib/python3.8/site-packages/flask/helpers.py", line 612, in send_file
    return werkzeug.utils.send_file(
  File "/usr/local/lib/python3.8/site-packages/werkzeug/utils.py", line 440, in send_file
    stat = os.stat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/app/app/data/todownload/timeseries.zip'
```


The traceback for the main gwasdiversitymonitor download is similar:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/app/app/routes.py", line 63, in getCSV
    return send_file('data/todownload/'+filename+'.zip')
  File "/usr/local/lib/python3.8/site-packages/flask/helpers.py", line 612, in send_file
    return werkzeug.utils.send_file(
  File "/usr/local/lib/python3.8/site-packages/werkzeug/utils.py", line 440, in send_file
    stat = os.stat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/app/app/data/todownload/timeseries.zip'

```

I checked inside the `gwas_flask` docker container for these files using `docker exec -it gwas_flask bash`. I found that they are in the following location within the container: `/app/data/todownload/`. This differs slightly from the path that the download buttons are pointing to (see tracebacks above). 

This should be a simple fix to modify the download path to look in the correct file location within the container. 

**Note:** There might be some headaches to make the path also work when running locally without docker, but our priority has to be functional docker containers for deployment.

**Comment by quentinGI** [comment]
@doug-leasure I've merged the by_funder branch to this defect branch - this should have solved the issue you were facing - however we might want to merge this branch back to the "by_funder" branch instead of the "dev" branch. Let me know what you think. Thanks

**Comment by gi-liam** [comment]
I have pulled the recent changes to the branch and rebuilt my docker containers but I am unable to replicate the issue you have reported. It appears that `app/` is being prepended in addition to the existing directory e.g `app/data/todownload/timeseries.zip` . Would be able to rebuild you local docker instance and see if the issue persists?

**Pull request merged**
