### PR TITLE
Feature/add report download button

### PR DESCRIPTION
**Pull request by quentinGI**

### CODE REVIEW

**Review by doug-leasure — CHANGES_REQUESTED** [review]
@quentinGI, could you please modify your pull request to merge into a branch other than `main`? 

If your changes are ready to be deployed on our development server, please merge into the `dev` branch (in which case, I will review in more detail before merging), otherwise please merge into one of the other working branches. Thank you!

**Review by doug-leasure — CHANGES_REQUESTED** [review]
Thanks, @gi-liam.  

I was initially unable to get the docker containers to build with these latest changes (or perhaps upstream changes?). I committed some minor tweaks 7db290d4b4191ede822d602becc20ac1bc509274 to this branch so that the `gwas_data` container builds, but the `gwas_flask` container is now throwing the following exception: 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/app/app/routes.py", line 40, in index
    tsPlot = dataLoader.getTSPlot()
  File "/app/app/DataLoader.py", line 212, in getTSPlot
    'ts_notrecorded_discovery_studies' : self.getTSPlotData("ts1_initial_count.csv"),
  File "/app/app/DataLoader.py", line 230, in getTSPlotData
    keys.remove("Year")
ValueError: list.remove(x): x not in list

```

Would you like to work on this bug on this branch before merging this pull request, or would you prefer to go ahead and merge into the `funders-report-header-layout` branch to follow-up there?

**Comment by crahal** [comment]
This is an upstream bug coming from some version control issues with generate_data.py. Suggested fix: just port in the entire current generate_data.py into this branch before merging.

**Comment by gi-liam** [comment]
I have added a the relative path of the reports PDFs (similar to [this](https://github.com/OxfordDemSci/gwasdiversitymonitor/pull/69/commits/5bb0070760cc7ba63f577b476125581fe9e58046) ) and updated the default button value to be in line with changes to filename e.g `All Studies` becomes `All Funders`

**Pull request merged**
