### PR TITLE
Updating The Requirements to fix #29

### LINKED ISSUE #29: Requirements.txt is out of date
Module Freeze has been removed from PyPi for a long time, all the core modules need updating. Its not currently possible to launch the project by fetching everything from requirements.txt without a little tinkering and manual updates.

### PR DESCRIPTION
**Pull request by Smilin-Dominator**
Removed 'freeze' and upgraded the rest (except requests-ftp which hasn't received an update)

### CODE REVIEW

**Comment by jdblischak** [comment]
Do you need to require the exact latest version of all the dependencies? This made it difficult to install the app using the conda-forge channel:

```
$ conda env create -n gdm --file requirements.txt
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - yattag==1.14.0
  - libsass==0.21.0
  - numpy==1.22.1
  - werkzeug==2.0.2

```

The conda-forge channel attempts to always have the latest versions of all PyPI packages available, but there can sometimes be a delay, especially for complex packages like numpy (they are working on 1.22.1).

https://github.com/conda-forge/numpy-feedstock/pull/254
https://github.com/conda-forge/numpy-feedstock/pull/255
https://anaconda.org/conda-forge/numpy/files
https://anaconda.org/conda-forge/yattag/files
https://anaconda.org/conda-forge/libsass/files
https://anaconda.org/conda-forge/werkzeug/files

I appreciate that you want to prevent the app breaking from future releases. You could protect yourself from this while allowing more flexibility by specifying upper and lower bounds. The following changes allow me to install with conda-forge:

```
libsass>=0.20,<0.22
numpy>=1.22,<1.23
Werkzeug>=2.0,<2.1
yattag>=1.13,<1.15
```

**Comment by Smilin-Dominator** [comment]
Thanks a lot for pointing this out! I'll add the changes you suggested and test them out with Conda.

**Comment by crahal** [comment]
Hi @Smilin-Dominator; If you wanted to test these changes I can review and approve!

**Comment by Smilin-Dominator** [comment]
Hi, sorry for the delay. I added upper and lower bounds to the requirements.

**Review by crahal — CHANGES_REQUESTED** [review]
Upon testing this on a vanilla venv, this gave me a traceback which was fixed by installing pathlib==1.0.1 which seemed to fix; is it possible for you to investigate this a little further?

**Comment by Smilin-Dominator** [comment]
Hi @crahal,

I tried to replicate your scenario by using the following commands on both Python 3.9.5 and 3.10.2 but didn't get a traceback.;
```sh
python -m venv venv
.\venv\scripts\activate
pip install --no-cache-dir -r .\requirements.txt
```
Could you please tell me what I'm missing?

It's worth mentioning that I'm using Windows. So I'll test using WSL and report back.

**Comment by Smilin-Dominator** [comment]
Small update, I tried the same with ZorinOS (using a Python 3.10.1 venv) and I still don't get a traceback. But, since there may be others who could experience this issue, I added `pathlib` and specified an upper and lower bound.

**Pull request closed without merging**
